### ISSUE TITLE
not sure how to use this bridge

### ISSUE THREAD

**Issue by avelampudi** [njh/mqtt-http-bridge#8]
I installed this mqtt-http-bridge in accordance to the "Getting Started" write up and then  continued to try out the examples using cURL. What I do not understand is that using curl, I'm directly publishing HTTP requests and when I open the localhost window, I see the general topics.

When I PUT posts to localhost:80/test, it shows up on the `bundle exec rackup -p 80` command window as `"PUT /test TTP/1.1" 200 1.251`, which is just fine. But nothing changes in the /test file of my localhost:80. 

My main question is how is this bridging from HTTP to MQTT and vice versa? How do I publish/subscribe from my mosquitto broker and use this bridge for HTTP requests?
I'm a newbie to the internet protocol area, and while it is fascinating, I find myself very confused. Please help me out!

**Comment by njh** [comment]
Are you running your own MQTT server, or using the pre-configured test.mosquitto.org?

What are you using for your MQTT client to test with?
Have you managed to get MQTT to work separately to this bridge?

**Comment by avelampudi** [comment]
@njh I would like to be able to do it both with my own server and the test.mosquitto.org server as well. I'm not sure how to subscribe to messages via mosquitto_sub and receive the messages I've PUT with cURL. How do I use the pre-configured server?

I am able to do the normal publishing and subscribing of topics with both my mosquitto and HiveMQ brokers as well as the hosted servers. I don't understand how to implement this bridge. The bridge is running on port 80, while my mosquitto runs on 1883. If you could describe how the bridging process is done or provide insight on how to to get my mqtt messages and http messages to interchange, that would be so helpful!

**Comment by njh** [comment]
There is documentation for mosquitto_pub and mosquitto_sub here:
* http://mosquitto.org/man/mosquitto_pub-1.html
* http://mosquitto.org/man/mosquitto_sub-1.html

The MQTT server hostname is configured here:
https://github.com/njh/mqtt-http-bridge/blob/master/mqtt-http-bridge.rb#L15

**Comment by avelampudi** [comment]
Oh, you have bridged the localhost to the online mosquitto server. Okay, got the HTTP PUT requests to show when I subscribe to the topic, but I have two questions here:

1) When I try to GET the retained value on the localhost:1234, I only get the last retained message sent via the HTTP request. When I use mosquitto_pub with QoS 2 and publish a message to the same topic on the test.mosquitto.org broker, how do I GET this message via HTTP through the localhost:1234. As of right now my bridging is only happening one way, when I want to PUT/POST, but what about receiving retained MQTT messages that I have sent in HTTP format? Does the bridge allow this? If it does, I can't figure it out.

2) If I want to use my local mosquitto broker, do I just change the server hostname to localhost:1883?

**Comment by njh** [comment]
1) Yes, you can only GET retained messages via HTTP. You can PUT/POST via HTTP and receive via MQTT subscribe.

2) Yes.

**Comment by avelampudi** [comment]
Ah. Do you plan on implementing the bridge so as to allow MQTT publishing to connect to the localhost:1234 and hence be able to GET those messages also or is this implementation purely only for PUT/POST?

**Comment by njh** [comment]
Hard to say with that limited information. You probably wouldn't want the lightbulb to poll the HTTP server.

If you are looking for a method of interconnecting different devices using lots of different protocol, then try Node-RED:

http://nodered.org/
